name: flutter_boilerplate
description: Flutter Boilerplate
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.17.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_bloc: 4.0.0
  fluro: 1.6.3
  get_it: 4.0.2
  built_value: 7.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.3
  bloc_test: 5.0.0
  mockito: 4.1.1
    
  build_runner: 1.10.0
  logging: 0.11.4
  built_value_generator: 7.0.7

flutter:
  uses-material-design: true